# Generated by Django 4.1.3 on 2023-02-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_bd', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='usuario',
        ),
    ]
