# Generated by Django 4.1.3 on 2023-02-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_bd', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
    ]
