# Generated by Django 4.1.3 on 2023-02-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_bd', '0003_remove_usuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(choices=[(1, 'especialidad 1,'), (2, 'especialidad 2'), (3, 'especialidad 3')], max_length=30),
        ),
    ]
